### ISSUE TITLE
Подключение

### ISSUE THREAD

**Issue by svin19** [yandex/YandexDriver#2]
Ребята, привет, закиньте пожалуйста инструкцию, как подключать этот драйвер в Java проекты. В идеале ссылку на класс в мавен репо и на документацию.

**Comment by EkS2018** [comment]
Прошу написать как подключать драйвер в питоне и селениум

**Comment by PetrovVadim** [comment]
I updated documentation

**Comment by lorashfuko** [comment]
Подскажите пожалуйста как подключить драйвер к Java проекту с  selenium?
На данный момент я добился того, что браузер Яндекс открывает стартовую страницу. Но он не открывает указанную страницу а в терминале сообщение "org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start."
Мой код
```
        System.setProperty("webdriver.chrome.driver", "/Applications/Yandex.app/Contents/MacOS/Yandex");
        ChromeOptions options = new ChromeOptions();
        options.setBinary("/Users/123/Documents/browserdriver/yandex/20.12.0.1065/yandexdriver");
        WebDriver driver = new ChromeDriver(options);
        driver.get("https://yandex.ru");
        driver.quit();
```
java 1.8.0_282
selenium 3.141.59
junit 4.13.1
MacOS.11.1
Яндекс 20.12.0.1065

**Comment by Heyter** [comment]
> Прошу написать как подключать драйвер в питоне и селениум

Знаю что поздно, но подключается точно так же как в Google Chrome.

**Comment by EkS2018** [comment]
Спасибо. 19.09.2021, 16:16, "Sam Nyashev" ***@***.***>: Прошу написать как подключать драйвер в питоне и селениумЗнаю что поздно, но подключается точно так же как в Google Chrome.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
